### ISSUE TITLE
Cookies with : in name

### ISSUE THREAD

**Issue by tjsail33** [hapijs/statehood#11]
As talked about in #56 of hapi-auth-cookie (https://github.com/hapijs/hapi-auth-cookie/issues/56), cookies with a colon in their name are causing errors about invalid cookie values. I do not believe that colons are invalid in cookie names, hence this issue.

**Comment by hueniverse** [comment]
cookie-name is a token per http://tools.ietf.org/html/rfc6265#section-4.1.1
token does not allow `:` per http://tools.ietf.org/html/rfc2616#section-2.2
