### ISSUE TITLE
Support SameSite attribute

### ISSUE THREAD

**Issue by geek** [hapijs/statehood#21]
This attribute has shipped with chrome 51, seems like a nice thing for statehood and hapi to support as well.

https://tools.ietf.org/html/draft-west-first-party-cookies-07#page-3

```
Set-Cookie: SID=31d4d96e407aad42; SameSite=Strict
```

Possible values are `None`, `Strict`, and `Lax` https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1.1

**Comment by hueniverse** [comment]
I'll take a PR
