### ISSUE TITLE
Cookies with the same name are ignored if only one is invalid

### ISSUE THREAD

**Issue by lukasolson** [hapijs/statehood#28]
I have a situation where there are multiple cookies with the same name (different paths) being sent in the request. If even just one of the cookies can't be decoded, the rest of the cookies (even if they can be decoded) are not returned.

Is this the desired behavior? If not, it seems like it could be fixed if `nextName()` was replaced with `nextArray()` here: https://github.com/hapijs/statehood/blob/master/lib/index.js#L228

**Comment by hueniverse** [comment]
Can you submit a PR with a test showing this issue?

**Comment by lukasolson** [comment]
@hueniverse https://github.com/hapijs/statehood/pull/29
