### ISSUE TITLE
Iron cookies password rotation is not supported by the current definition

### ISSUE THREAD

**Issue by wzrdtales** [hapijs/statehood#44]
Currently it is not possible to utilize Irons password rotation, since there is no way to provide the actual list of rotated passwords.

Would be willing to open a PR for it, but wanted to firstly ask if you would be willing to get this supported or if you do not want it to be supported.

**Comment by wzrdtales** [comment]
ping @hueniverse

**Comment by hueniverse** [comment]
What's blocking you? The validation rules for `password` allow any object to be passed.

**Comment by wzrdtales** [comment]
Yeah you're right, forgot to update, I figured out that you can actually format the object like that, to make it work:

```
    {
      id: 2,
      secret: 'secret',
      '1': {
        secret: 'secret1'
      },
      '2': {
         secret: 'secret'
      }
    }
````

Was just a bit confused, since there is no documentation yet about rotation, and the comments misleaded me a bit https://github.com/hueniverse/iron/blob/fa731cc24d3572a4e002281f92f7f3e768a80d76/lib/index.js#L245

But got it working though :). Thanks for your response!

**Comment by hueniverse** [comment]
I'll make it more intuitive.
