### ISSUE TITLE
security vulnerability caused by cryptiles@4.1.1

### ISSUE THREAD

**Issue by filipesantoss** [hapijs/statehood#45]
In our project, Snyk reported `cryptiles@4.1.1` as a dependency with a known security vulnerability
The latest version of cryptiles (4.1.2) seems to have fixed this vulnerability.

More info about the (medium severity) vulnerability in `cryptiles@4.1.1` can be found at
https://snyk.io/vuln/npm:cryptiles:20180710

**Comment by WesTyler** [comment]
This library is already using `"cryptiles": "4.x.x"`, which will pull 4.1.2.

I think the Github security alerts just don't understand the `.x.x` version syntax. We had similar issues with the Hoek alerts this summer.
